title: Sarah Schwartz # your name (or website title) here
logo: "/images/self.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data analyst who is working on documenting my expanding data science skills.
  <br><br>
  I have a Bachelor's Degree in Mathematics from the University of Southern Indiana, and a Master's Degree
  in Physics from Michigan State University. 
  <br><br>
  My education and experience gives me a unique prospective when it comes to data analysis.
  <br><br>
  
  <strong>Continuing Education:</strong>
  <br><br>
  <a href="https://www.credly.com/badges/f038f910-45b2-4ec6-8f71-e4e7238e2c96/public_url">Google Data Analytics Professional Certificate</a> 
  <br><br>
  <a href="https://www.udemy.com/certificate/UC-b2e9e0a3-2aa5-4bda-97fb-f657c2b09632/">2022 Complete Python Bootcamp From Zero to Hero in Python</a>
  
  <strong>Links:</strong>
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-schwartz-data/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://public.tableau.com/app/profile/sarah4232#!/">View My Tableau Public Profile</a> 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
